<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($query) {
            $query->user_id = auth()->id();
        });
    }

    protected $fillable = [
        'user_id',
        'name',
        'description',
        'price',
        'tasks_done',
        'start',
        'finish'
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function tasks() {
        return $this->hasMany(Task::class);
    }
}

